language: node_js

node_js:
  - "8"

cache: npm

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: book
  on:
    branch: master
  target_branch: gh-pages