language: node_js

node_js:
  - "8"

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ba4da0726fcb8502b25c2a5bb1306bf6411fcaac
  local_dir: book
  on:
    branch: master
  target_branch: gh-pages